FROM public.ecr.aws/nginx/nginx-unprivileged:1.29-alpine@sha256:0c79d56aee561a1d81c63f00eee5fb5fe29279560cdc55e91425133104c7fbe6
ARG APP_VERSION=dev
LABEL org.opencontainers.image.title="WyanDesk" \
      org.opencontainers.image.version="${APP_VERSION}"
COPY wyan-desk/nginx.conf /etc/nginx/conf.d/default.conf
COPY wyan-desk/dist /usr/share/nginx/html
EXPOSE 8080
